
**<center>ASSOCIATION RULE LEARNING USING APRIORI ALGORITHM</center>**

**Aim:**

 To associate rule learning using Apriori Algorithm with support threshold = 8% and confidence threshold =50%

**Description:**

Association rule learning works on the concept of If and Else Statement, such as if A then B.
If element is called antecedent, and then statement is called as Consequent.
To measure the associations between thousands of data items, there are several metrics.  

> Lift (x => y) = 1 means that there is no correlation within the itemset.

> Lift (x => y) > 1 means that there is a positive correlation within the itemset, i.e., products in the itemset, x and y, are more likely to be bought together.

> Lift (x => y) < 1 means that there is a negative correlation within the itemset, i.e., products in itemset, x and y, are unlikely to be bought together.

**Code:**

In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Datasets/Shop2.csv")
t_df = df.Item.str.split(",")
df.head()

   TID                                               Item
0    1     Lassi,Coffee Powder,Butter,Yougurt,Ghee,Cheese
1    2                                 Ghee,Coffee Powder
2    3                     Lassi,Tea Powder,Butter,Cheese
3    4  Cheese,Tea Powder,Panner,Coffee Powder,Butter,...
4    5    Cheese,Yougurt,Coffee Powder,Sugar,Butter,Sweet

In [ ]:
def count_item(t_df):
  count_ind_item = {}
  for row in t_df:
    for i in range(len(row)):
      if row[i] in count_ind_item.keys():
        count_ind_item[row[i]] += 1
      else:
        count_ind_item[row[i]] = 1
  data = pd.DataFrame(list(count_ind_item.items()),columns = ['item_sets','supp_count'])
  return data

def prune(data,supp):
  df=data[data.supp_count>=supp]
  return df
list_of_items=list(prune(count_item(t_df),9).item_sets)

In [ ]:
def join(list_of_items,count):
  itemsets = []
  i=1
  for entry in list_of_items:
    proceding_items = list_of_items[i:]
    for item in proceding_items:
      if type(item) is str:
        if entry!= item:
          tuples = (entry,item)
          itemsets.append(tuples)
      else:
        tuples=set(entry).union(item)
        if(len(tuples)==count):
          itemsets.append(tuple(sorted(tuples)))
    i = i+1
  return itemsets
itemsets=join(list_of_items,2)
itemsets1=join(itemsets,3)
itemsets2=join(itemsets,4)

In [ ]:
def count_itemset(t_df,itemsets):
  count_item = {}
  for item_set in itemsets:
    count_item[item_set] = 0
    set_A = set(item_set)
    for row in t_df:
      set_B = set(row)
      if set_B.intersection(set_A) == set_A:
        if item_set in count_item.keys():
          count_item[item_set] +=1
        else:
          count_item[item_set] = 1
    data = pd.DataFrame(list(count_item.items()),columns = ['item_sets','supp_count'])
    return data
df=count_itemset(t_df,itemsets2)
df

                                 item_sets  supp_count
0  (Butter, Coffee Powder, Lassi, Yougurt)           3

In [ ]:
ind=count_item(t_df)
confidence=pd.DataFrame(columns=['item_set','confidence'])
for row in df.item_sets:
  for i in range(len(row)):
    for j in range(len(row)):
      if i!=j and j>i:
        tuples=(row[i],row[j])
        value1=df[df.item_sets==row].supp_count
        d=set(row).difference(set(tuples))
        value2=ind[ind.item_sets==list(d)[0]].supp_count
        value3=count_itemset(t_df,[tuples]).supp_count
        conf=round(int(value1)/int(value2)*100,2)
        st=(tuple(d),'->',tuples)
        new_row={'item_set':st,'confidence':conf}
        confidence=confidence.append(new_row,ignore_index=True)
        conf=round(int(value1)/int(value3)*100,2)
        st=(tuples,'->',tuple(d))
        new_row={'item_set':st,'confidence':conf}
        confidence=confidence.append(new_row,ignore_index=True)
confidence

                                           item_set  confidence
0   ((Yougurt, Lassi), ->, (Butter, Coffee Powder))       33.33
1   ((Butter, Coffee Powder), ->, (Yougurt, Lassi))       37.50
2   ((Yougurt, Coffee Powder), ->, (Butter, Lassi))       33.33
3   ((Butter, Lassi), ->, (Yougurt, Coffee Powder))       42.86
4   ((Coffee Powder, Lassi), ->, (Butter, Yougurt))       18.75
5   ((Butter, Yougurt), ->, (Coffee Powder, Lassi))       37.50
6   ((Yougurt, Butter), ->, (Coffee Powder, Lassi))       33.33
7   ((Coffee Powder, Lassi), ->, (Yougurt, Butter))       42.86
8   ((Butter, Lassi), ->, (Coffee Powder, Yougurt))       21.43
9   ((Coffee Powder, Yougurt), ->, (Butter, Lassi))       42.86
10  ((Butter, Coffee Powder), ->, (Lassi, Yougurt))       21.43
11  ((Lassi, Yougurt), ->, (Butter, Coffee Powder))       75.00

In [ ]:
confidence.loc[confidence.confidence>=50]

                                           item_set  confidence
11  ((Lassi, Yougurt), ->, (Butter, Coffee Powder))        75.0

**Result:**

Association rule learning using Apriori Algorithm has been implemented on the given dataset successfully.